name: Python CI with uv and Data Caching

# This workflow runs on pushes to the main branch and on pull requests.
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Cache uv
      uses: actions/cache@v3
      with:
        path: ~/.cache/uv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/requirements.txt') }}

    - name: Install dependencies
      run: uv pip install -r requirements.txt

    - name: Cache data
      id: cache-data
      uses: actions/cache@v3
      with:
        path:
          - hcp.zip
          - 1kb.zip
        key: ${{ runner.os }}-data-${{ hashFiles('aaicd.py') }}

    - name: Download data
      if: steps.cache-data.outputs.cache-hit != 'true'
      run: python aaicd.py download

    - name: test cache
      run: ls -lh *.zip
